name: CI

on:
  pull_request:
    branches: ['develop']

jobs:
  unit-test:
    name: Unit Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Yarn install
        run: yarn

      - name: Run Eslint Test
        run: yarn test:lint

      - name: Create Artifact
        run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
