name: CI

on:
  pull_request:
    branches: ['develop']

jobs:
  unit-test:
    name: Unit Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Yarn install
        run: yarn

      - name: Run Eslint Test
        run: |
          ESLINT_DIFF_COMMIT=$(git diff HEAD HEAD^ --name-only src/)
          yarn eslint $ESLINT_DIFF_COMMIT
