name: CI

on:
  pull_request:
    branches: ['develop']

jobs:
  install-node:
    name: Install NodeJs
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Run install
        uses: borales/actions-yarn@v4

  test:
    name: Test format code
    runs-on: ubuntu-latest
    needs: install-node
    steps:
      - name: Test Eslint
        run: yarn lint-staged
