name: Build Android

on:
  push:
    branches: ['develop']

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: zulu
          # architecture: x64
          # cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # - name: Check out repository code
      #   uses: actions/checkout@v3

      # - name: Run Yarn install
      #   run: yarn
