name: Build Android

on:
  push:
    branches: ['develop']

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: zulu
          architecture: x64
          cache: gradle

      - name: Validate Gradlew
        uses: gradle/wrapper-validation-action@v1

      - name: Run Yarn install
        run: yarn

      - name: Build start
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          cd ..

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Android Release APK
          path: android/app/build/outputs/apk/release/app-release.apk
